//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asrama_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string NIK { get; set; }
        public string NamaCust { get; set; }
        public string TelpNum { get; set; }
        public string TipeKamar { get; set; }
        public string Durasi { get; set; }
        public string KamarNum { get; set; }
        public string NamaKer { get; set; }
        public string KerTelpNum { get; set; }
        public string TglMasuk { get; set; }
    }
}
